"""
Measurement Folder Cleanup Utility
==================================
Wipes all files and directories generated by the pipeline scripts,
leaving only the raw data (video1.avi and the export/ folder).
Run this before starting a fresh hyperparameter sweep.
"""

import os
import shutil
import logging
from pathlib import Path

logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

# --- CONFIGURATION ---
PROJECT_DIR = Path(__file__).resolve().parent.parent
MEASUREMENTS_DIR = PROJECT_DIR / "measurements"

# Define the exact items we want to delete
GENERATED_ITEMS = [
    "detections.csv",           # From annotation_pipeline
    "video1_annot.mp4",        # From annotation_pipeline
    "bev_images",              # Directory from grid_mapping_pipeline
    "time_sync.csv",           # Debug file from fusion_pipeline
    "detections_synced.csv",   # Debug file from fusion_pipeline
    "radar_synced.csv",        # Debug file from fusion_pipeline
    "fusion_bev.mp4"           # Visualisation from fusion_pipeline
]

def purge_generated_data():
    if not MEASUREMENTS_DIR.exists():
        logging.error(f"Directory not found: {MEASUREMENTS_DIR}")
        return

    logging.info(f"🧹 Starting cleanup in: {MEASUREMENTS_DIR}")
    
    # Iterate through all subfolders in the measurements directory
    folders = [f for f in MEASUREMENTS_DIR.iterdir() if f.is_dir() and f.name not in ["reference_points", "ref_pts"]]
    
    total_deleted = 0

    for folder in folders:
        logging.info(f"Checking: {folder.name}")
        
        for item_name in GENERATED_ITEMS:
            item_path = folder / item_name
            
            if item_path.exists():
                try:
                    if item_path.is_dir():
                        shutil.rmtree(item_path)
                        logging.info(f"  [-] Deleted Directory: {item_name}")
                    else:
                        os.remove(item_path)
                        logging.info(f"  [-] Deleted File:      {item_name}")
                    total_deleted += 1
                except Exception as e:
                    logging.error(f"  [!] Error deleting {item_name}: {e}")

    # Also wipe the final consolidated dataset if it exists
    dataset_dir = PROJECT_DIR / "dataset"
    if dataset_dir.exists():
        logging.info("🧹 Wiping the consolidated /dataset folder...")
        shutil.rmtree(dataset_dir)

    logging.info("="*40)
    logging.info(f"CLEANUP COMPLETE! Total items removed: {total_deleted}")
    logging.info("Raw data (video1.avi and export/) remains untouched.")
    logging.info("="*40)

if __name__ == "__main__":
    confirm = input("This will delete ALL generated labels and images in your measurements folders. Are you sure? (y/n): ")
    if confirm.lower() == 'y':
        purge_generated_data()
    else:
        logging.info("Cleanup cancelled.")